name: dependabot
on:
    pull_request
jobs:
    approve:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        steps:
            - uses: hmarr/auto-approve-action@v2.0.0
              with:
                  github-token: "${{ secrets.DIST_TOKEN }}"
    merge:
        runs-on: ubuntu-latest
        needs: approve
        steps:
            - name: Merge PR
              uses: ridedott/merge-me-action@v1.3.18
              with:
                  GITHUB_TOKEN: ${{ secrets.DIST_TOKEN }}
